from typing import Protocol, Sequence, TypeVar, Optional
from user import User

T = TypeVar('T')

class IDataRepository(Protocol[T]):
    def get_all(self) -> Sequence[T]: ...
    def get_by_id(self, id: int) -> Optional[T]: ...
    def add(self, item: T) -> None: ...
    def update(self, item: T) -> None: ...
    def delete(self, item: T) -> None: ...

class IUserRepository(IDataRepository[User], Protocol):
    def get_by_login(self, login: str) -> Optional[User]: ...

class IAuthService(Protocol):
    @property
    def is_authorized(self) -> bool: ...
    @property
    def current_user(self) -> Optional[User]: ...
    def sign_in(self, user: User) -> None: ...
    def sign_out(self, user: User) -> None: ...
